BUNDLE_NAME = musicfg
musicfg_BUNDLE_ID = musicfg
musicfg_INSTALL_PATH = /Library/PreferenceBundles
musicfg_FRAMEWORKS = UIKit CoreGraphics
musicfg_PRIVATE_FRAMEWORKS = Preferences
musicfg_FILES = musicfgRootListController.m
musicfg_RESOURCE_FILES = Root.plist Info.plist icon.png icon@2x.png icon@3x.png

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
